name: Deploy Wedding Invitation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Replace API Key
      run: |
        # API 키를 환경변수로 교체
        sed -i "s/AIzaSyBjC49GENw6YNu7l0RtAwPYLda97fhjqL0/${{ secrets.GOOGLE_MAPS_API_KEY }}/g" invitation.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
